#!/bin/bash
degree=$1
field=$2
base_dir="${HOME}/ecnf-data/$1"
echo base directory: ${degree}
echo field: ${field}
sage_out="sage.out.$1.$2"
echo sage output file: ${sage_out}
cline="from files import extend_mwdata; extend_mwdata('${base_dir}','${field}', verbose=True)"
echo ${cline} | sagedev -q > ${sage_out}

# Use with parallel as follows:
#
#
# parallel -j 5 --joblog ar.log --progress ./runar RQF :::: RQF.txt
#
# 5 parallel jobs, data in RQF/, list of fields in RQF.txt
#
